version: '3'
services:
  webapp:
    build: .
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      - ./uploaded-files:/path/in/container
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    environment:
      POSTGRES_DB: AITutorDB
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d AITutorDB"]
      interval: 10s
      timeout: 5s
      retries: 5
